### ISSUE TITLE
[Bug]: Wafris logs connection error even when it is not enabled

### ISSUE THREAD

**Issue by jmadlena** [Wafris/laravel-wafris#5]
### What happened?

For local development I have Wafris disabled. But I see a Wafris connection error in my logs for every request, which can clutter it up and make it hard to read.

```
Wafris error: Connection refused [tcp://127.0.0.1:6379]
```

### How to reproduce the bug

1. Install Wafris per the readme in a Laravel 10 application
2. Disable Wafris (wafris.enabled = false)
3. Make a request

### Package Version

0.0.2

### PHP Version

8.2.14

### Laravel Version

10.40

### Which operating systems does with happen with?

macOS

**Comment by rmcastil** [comment]
@jmadlena thanks for this feedback. I'll start working on a patch to suppress these messages.

**Comment by jmadlena** [comment]
@rmcastil Thanks! Let me know if I can do anything to help.

**Comment by rmcastil** [comment]
If you want it sooner than later you could submit a PR. We don’t have an
official Laravel maintainer so I’m usually having to carve out extra
time to make sure I’m doing the Laravel stuff right. 

We would of course add you to the contributor list. 

On January 11, 2024, GitHub ***@***.***> wrote:
> @rmcastil <https://github.com/rmcastil> Thanks! Let me know if I can
> do anything to help.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/Wafris/laravel-wafris/issues/5#issuecomment-
1888073825>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AABF6M6OEO3BGI3VRA3TY2LYOBR63AVCNFSM6AAAAABBVFJPGWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBYGA3TGOBSGU>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by jmadlena** [comment]
I could certainly take a crack at it. I'll make a PR for you review soon.

**Comment by MiniCodeMonkey** [comment]
I went ahead and PR'ed a fix for this 🙌

**Comment by rmcastil** [comment]
Thanks Mathias! Merged.

**Comment by jmadlena** [comment]
@rmcastil Since this was merged, will a new release be tagged so it can updated via composer like normal?

**Comment by rmcastil** [comment]
@jmadlena yup! Will try and get to that today.
